name: Daily Go Check
on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *" # every day at 8AM UTC
jobs:
  check-go-version:
    if: github.repository_owner == 'go-nv'
    strategy:
      matrix:
        os: ["ubuntu-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: master
          token: ${{ secrets.GH_TOKEN }}
      - name: Install JQ
        run: sudo apt install jq
      - name: Remove golang
        run: sudo rm -rf $(which go)
      - name: Add goenv to PATH
        run: export PATH="$PATH:./bin/goenv"
      - name: Check latest version of Go against Goenv
        run: ./scripts/latest_version.sh
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
