name: Release Drafter

on:
  workflow_dispatch:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - master
      - v3
  # pull_request event is required only for autolabeler
  pull_request:
    branches:
      - master
      - v3
    # Only following types are handled by the action, but one can default to all as well
    types:
      - opened
      - reopened
      - synchronize
  # pull_request_target event is required for autolabeler to support PRs from forks
  pull_request_target:
    branches:
      - master
      - v3
    types:
      - opened
      - reopened
      - synchronize

permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      # permissions required for triggering the dispatch workflow
      actions: write
      # write permission is required to create a github release
      contents: write
      # write permission is required for autolabeler
      # otherwise, read permission is required at least
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Determine config file
        id: config
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/v3" ]] || [[ "${{ github.base_ref }}" == "v3" ]]; then
            echo "config-name=release-drafter-v3.yml" >> $GITHUB_OUTPUT
          else
            echo "config-name=release-drafter.yml" >> $GITHUB_OUTPUT
          fi

      # Drafts your next Release notes as Pull Requests are merged into "master" or "v3"
      # TODO: Switch back to official action when this PR is merged: https://github.com/release-drafter/release-drafter/pull/1459
      # - uses: release-drafter/release-drafter@v6
      - uses: ChronosMasterOfAllTime/release-drafter@honor_version_template
        # (Optional) specify config name to use, relative to .github/. Default: release-drafter.yml
        with:
          config-name: ${{ steps.config.outputs.config-name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Dispatch Pre-Release Job
        if: github.event_name == 'push' && github.ref_name == 'master'
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Pre Release
          token: ${{ secrets.GH_TOKEN }}
